Feature: base shapash report
MAIF/shapash pull request #148
Opened 2021-03-17 10:09 UTC by ThibaudReal

# Description

This PR enhances the Shapash base Report by adding the following features : 
- :white_check_mark: -  New section : _Global explainability of the model_
- :white_check_mark: -  New section : _Model performance_
- :white_check_mark:  - 2 Dropdown menus to select the feature to be displayed (in explainability and univariate analysis sections) implemented in Javascript
- :white_check_mark: -  Improving page layout
- :white_check_mark: -  Improving the univariate plots for general case (when too many categories, 'other' category displayed, truncating labels too long...) 

This PR also includes commits merged in master as it was necessary for some features (title of the report).

Unit tests and docstring will be added soon as we are now more confident about the technologies used for the report.

Preview of the report so far : 

![image](https://user-images.githubusercontent.com/48520594/111450417-a6a52780-8710-11eb-8e8c-2606e1c0cca8.png)
![image](https://user-images.githubusercontent.com/48520594/111450516-c2a8c900-8710-11eb-91c1-1225d4c203d0.png)
![image](https://user-images.githubusercontent.com/48520594/111450571-d05e4e80-8710-11eb-96a2-15efbf188646.png)
![image](https://user-images.githubusercontent.com/48520594/111450640-e23ff180-8710-11eb-9468-3d0d41e72695.png)

2021-03-17 18:07 UTC, MaxGdr approved these changes

2021-03-17 18:08 UTC, MaxGdr requested changes
Conflict to resolve on model.py before merge

2021-03-19 09:09 UTC, yg79 approved these changes

2021-03-22 09:07 UTC, MaxGdr approved these changes

2021-03-23 09:40 UTC, merged

2021-03-23 09:41 UTC, ThomasBouche approved these changes